### ISSUE TITLE
Doesn't work on client side

### ISSUE THREAD

**Issue by sonaye** [gtklocker/bittrex-orderbook#7]
<img width="600" alt="screen shot 2017-12-26 at 5 57 49 am" src="https://user-images.githubusercontent.com/23000873/34345731-2b8ab726-ea02-11e7-8df8-f41dad2c8df8.png">

To reproduce:

app/package.json
```json
{
  "dependencies": {
    "bittrex-orderbook": "2.0.5",
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-scripts": "1.0.17"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build"
  }
}
```

app/src/index.js
```javascript
import { render } from 'react-dom';

render(null, document.getElementById('root'));

// ..

const Book = require('bittrex-orderbook');

const book = new Book();

book
  .market('USDT-BTC')
  .on('bidUpdate', market => console.log('bids', market.bids.top(5)));

book
  .market('USDT-BTC')
  .on('askUpdate', market => console.log('asks', market.asks.top(5)));
```

app/public/index.html
```html
<div id="root"></div>
```

`cd app && yarn && yarn start` or `cd app && npm i && npm start`

**Comment by sonaye** [comment]
I am investigating this.

**Comment by sonaye** [comment]
`bittrex-orderbook` depends on `signalr-client`, which depends on `websocket`.

As stated in [signalr-client](https://github.com/mwwhited/signalr-client-nodejs) and [websocket](https://github.com/theturtle32/WebSocket-Node/issues/298) repos:
> This is a node.js service client. It is not supported within a web browser.

> This library is a WebSocket implementation for Node, not for browsers.

**Possible solution**
- Rewrite [connection.js](https://github.com/gtklocker/bittrex-orderbook/blob/master/src/connection.js) to work with [signalr-no-jquery](https://github.com/DVLP/signalr-no-jquery).
- `BittrexConnection` would accept a browser constructor parameter that can be set to true.
```javascript
new BittrexConnection() // node implementation with signalr-client (current)
new BittrexConnection(true) // browser implementation with signalr-no-jquery
```

Unfortunately, the APIs are different. Here is a summary of how they differ (from a quick glance to the code I could be wrong, didn't test).
```javascript
// signalr-client API

const client = new singalR.client('wss://socket.bittrex.com/signalr', ['CoreHub'], 10, true);
client.headers = headers; // needed for cloudscraper

client.start();
client.call('CoreHub', 'SubscribeToExchangeDeltas', opts); // should be called when start() returns ready

client.on('CoreHub', 'QueryExchangeState', cb);
client.on('CoreHub', 'updateExchangeState', cb);

// signalr-no-jquery API

const connection = hubConnection('wss://socket.bittrex.com/signalr', { headers });
const client = connection.createHubProxy('CoreHub');

connection
  .start()
  .done(() => client.invoke('SubscribeToExchangeDeltas', opts)))
  .fail(cb);

client.on('QueryExchangeState', cb);
client.on('updateExchangeState', cb);
```

Possible sources of documentation:
- [signalr-client](https://github.com/mwwhited/signalr-clientnodejs/tree/master/WhitedUS.SignalR/WhitedUS.signalR)
- [react-native-signalr](https://github.com/olofd/react-native-signalr)

I might revisit this soon.

**Comment by sonaye** [comment]
It looks like we might have another issue after that, see https://github.com/codemanki/cloudscraper/issues/33. From your experience, does the connection completly fails without `cloudscraper`?

I have already implemented a decent order book with the `/public/getorderbook` endpoint from the rest API, I am refetching every n seconds, which is not the best solution but it works for now, this is why I've been looking into this package.

Plan B if none of this works: [App Engine](https://cloud.google.com/community/tutorials/run-expressjs-on-google-app-engine) or [Heroku](https://devcenter.heroku.com/articles/node-websockets).

**Comment by gtklocker** [comment]
Hey @sonaye, thanks for looking into this.

While client-side compatibility would only be a nice to have for my personal use case I'd be pretty interested in seeing it developed. Let me address each one of your points here:

* signalr library: I've actually been looking to move from the signalr library we're using. Unfortunately it seems like there are no real high quality signalr libraries other than the official one which is one designed for browser use. Using 2 libraries depending on the context doesn't seem like a good way of solving this, switching to `signalr-no-jquery` or something similar would be fine though and maybe even encouraged.
* cloudscraper: This is actually a recent one, as you can see on issue #3. Unfortunately we have to have this, because even if they temporarily don't require Cloudflare authentication they're pretty liberal in doing so: we're using an unofficial API. I think removing this for the sake of client-side would really impair the functionality of the library and is probably not worth it.

I'm going to close this for now but feel free to comment back if you have any other idea.
